export const APP_CONSTANTS = {
  TIMEZONE: 'Europe/Warsaw',
  DATE_FORMAT: 'yyyy-MM-dd',
  TIME_FORMAT: 'HH:mm',
  EARLIEST_RESERVATION_TIME: '08:00',
  LATEST_RESERVATION_TIME: '23:00',
  MAX_RESERVATION_DURATION_HOURS: 5
} as const;
